version: '2'
services:
  flask:
    env_file:
      - ./.env
    build: ./flask
    image: flask
    volumes:
      - ./flask:/app
    command: uwsgi --socket flask:${FLASK_PORT} --wsgi-file app.py --callable app
    environment:
      BOKEH_URL: 'http://${HOST_ADDRESS}:80/bokeh'
  bokeh:
    env_file:
      - ./.env
    build: ./bokeh
    image: bokeh-serve
    volumes:
      - ./bokeh/sliders.py:/app/sliders.py
    command: --prefix bokeh --address 0.0.0.0 --port ${BK_PORT} --num-procs 0 --allow-websocket-origin=* sliders.py
  nginx:
    image: nginx:1.21.3
    env_file:
      - ./.env
    volumes:
      - ./nginx/generate_conf.sh:/tmp/generate_conf.sh
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:${NGINX_PORT}"
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=${NGINX_PORT}
      - FLASK_UWSGI_PASS=flask:${FLASK_PORT}
      - BOKEH_PROXY_PASS=http://bokeh:${BK_PORT}/bokeh
    command: /bin/bash -c "/tmp/generate_conf.sh && nginx -g 'daemon off;'"
    links:
      - flask:flask
      - bokeh:bokeh
